### ISSUE TITLE
BUG version returned is representative of SiteTree or Page vs the actual class of the page

### ISSUE THREAD

**Issue by muskie9** [silverstripe-labs/silverstripe-sharedraftcontent#155] opened 2021-10-15 03:53 UTC
We noticed this issue while attempting to review a draft page which had an ElementalArea relation. Elements were not displaying when previewing the page via the share link.

After reviewing `ShareDraftController::preview()` it seems getting the page by stage and not specifying the final class of that page prevents some relations from loading.

Taking inspiration from Elemental, is it worth tracking the page's `ClassName` on the `ShareToken` allowing for an accurate versioned query which would include anything on that subclass vs simply querying with the `SiteTree` classname? I'm not sure how this would work out with semvar, however in some preliminary testing mucking around with the method, and that query specifically, querying the specific class via `Versioned::get_by_stage()` seems to render added relations/fields as expected.

**Comment by michalkleiner** [comment] 2021-10-15 04:24
I'd say in general using the correct class of the page is better, so any enhancement toward that goal would be good. If we can provide a test or at least replications steps to compare the behaviour before/after the fix, that would help.

**Comment by muskie9** [comment] 2021-10-18 19:43
I'm working through replication steps and in a base install the missing draft content may not be quite as widespread as initially thought. I hope to provide more context as to what scenarios have missing draft content at least in a manual format.

To demonstrate the issue in test form before a fix, would that simply be opening a PR with a test to affirm the issue?

**Comment by muskie9** [comment] 2021-10-18 20:43
So after some further digging it appears that out of the box the functionality works as expected. The specific issue we have run into is related to `BlogPost` and its implementation of `canView`. The `canView` method will return false if viewing a shared draft content link and the post's `PublishDate` is not set, or is set to a future date/time.

I'm not sure if there are additional performance benefits to querying the appropriate class as first noted, however I'm happy to continue that work even though the underlying issue is unrelated to that query specifically. This does seem to shed light on (technically) expected behavior, however confusing to a CMS user due to underlying `can` logic they may not be totally aware of.

Should a CMS user be able to schedule a blog post for the future, have it in draft state, and share a link via this module and expect the post to display as intended for those visiting the link seems to be the question. If that is the case then it may be a larger question of how this module can work more with the `canView` method in the event a developer has implemented custom `canView` logic as that logic could take any form really.

**Comment by nathanbrauer** [comment] 2023-09-09 06:27
Possible duplicate of #112

**Comment by GuySartorelli** [comment] 2023-09-11 00:40
Given the additional context, I agree that this is a duplicate of #112. Closing.

**Closed as not planned by GuySartorelli** 2023-09-11 00:40 UTC
Labels: type/bug, complexity/medium, impact/medium
