### ISSUE TITLE
Viewing preview URL logs out current user

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe-labs/silverstripe-sharedraftcontent#160] opened 2022-02-27 21:44 UTC
When you follow a shared draft link and you are logged in, it will logged you out.

This was identified via this issue: https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/153#issuecomment-1050699391

> This appears to clash with Session::$strict_user_agent_check (on by default), the session is invalidated on viewing a preview/ URL due to the change in UA string.

### ACs
- [x] When following a shared draft link the user remains logged in
- [x] The previous [bugfix](https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/153) remains in place

##PR
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/168

**Comment by sabina-talipova** [comment] 2022-06-07 01:09
I couldn't reproduce this issue in the local environment. 
I've done the following steps:
1. Opened CMS in general browser window.
2. Logged in CMS as ADMIN user.
3. Opened Page in Draft Mode and clicked Share button at the bottom of Preview section.
4. Copied link
5. Opened CMS in Incognito browser window.
6. Log in CMS as "Content author" user.
7. In new tab in Incognito window and input link.
8. Refresh page in tab where admin section is open. Still logged in.
9. Went to admin section in the tab where Preview link was open. Still logged in.

Probably, this issue was solved.

**Comment by sabina-talipova** [comment] 2022-06-08 00:55
Close prior PR. Had issues with unexpected commits after rebase. Open new PR https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/168

**Comment by GuySartorelli** [comment] 2022-06-08 06:30
Linked pr is merged.

**Closed as completed** 2022-06-08 19:49 UTC
Labels: type/bug, impact/high
