### ISSUE TITLE
Share draft button broken in 3.2

### ISSUE THREAD

**Issue by scott1702** [silverstripe-labs/silverstripe-sharedraftcontent#31] opened 2015-05-18 03:00 UTC
Styling of share draft button is broken in 3.2

![image](https://cloud.githubusercontent.com/assets/10215604/7673799/744b0d5e-fd6e-11e4-959f-a781fb7fa563.png)

**Comment by flashbackzoo** [comment] 2015-05-18 05:54
It's caused by this https://github.com/silverstripe/silverstripe-framework/commit/730c4d37

`.chzn-container` gets set to `display: block` on line 226.

**Comment by tractorcow** [comment] 2015-05-26 01:50
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4203

**Closed by tractorcow** 2015-05-26 01:50 UTC
